### ISSUE TITLE
Homepage: Distorted background image of the content section and the two red buttons in IE 7 browser.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#105]
![image](https://cloud.githubusercontent.com/assets/11186304/7267077/84c2a4f8-e8e7-11e4-87d2-1cffe82fe2b1.png)

**Comment by christiancebudigital** [comment]
please clear cache.. working on my end...
![ie7](https://cloud.githubusercontent.com/assets/11186331/7268018/8c58a582-e8f6-11e4-9a0b-3cc5d940e391.jpg)
