### ISSUE TITLE
Inner pages - Right sidebar: Unable to manage (change/update) the attached PDF file of the 'Venue Menu' at the backend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#126]
![image](https://cloud.githubusercontent.com/assets/11186304/7316458/c9ef5080-eaa9-11e4-986b-bcd6ba7a4dba.png)

**Comment by christiancebudigital** [comment]
we changed this one as page link in acf, because design specs didnt state that it will be pdf button, if we make this one pdf, it will have redundant content on  left side bar menu..
