### ISSUE TITLE
Homepage: Find Out About Us button is currently linked to About Us page. There's no PSD layout provided for the About us page.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#130]
![image](https://cloud.githubusercontent.com/assets/11186304/7366652/673d0074-edcc-11e4-8888-a02ad805e4de.png)

**Comment by christiancebudigital** [comment]
FROM Jolene,
"Hi Chris 
The About us page is the Hit Studio Karaoke page, http://hit-studio.stage.titanweb.com.au/hit-studio-karaoke/"
