### ISSUE TITLE
Homepage - Content, Buttons, Footer sections: Padding left and right of the contents container should align to the leadins section above as per design specs. Please apply this to all pages.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#39]
![image](https://cloud.githubusercontent.com/assets/11186304/7081374/7626d6d0-df73-11e4-9f1d-e9015f519cd9.png)

**Comment by christiancebudigital** [comment]
leadins only apply to homepage..

**Comment by maluzynel** [comment]
Not totally fixed. Please refer to the PSD layout for the design specs alignment and match up to the actual implementation. Leadins section should align to the company logo above. H1 title, contents, two buttons and footer section should align to the leadins section except for the 'Book a karaoke room today' section.

**Comment by maluzynel** [comment]
Leadins section in the homepage should align to the company logo above.

![image](https://cloud.githubusercontent.com/assets/11186304/7247626/031d033e-e83e-11e4-88f8-b4a466403f6b.png)
