### ISSUE TITLE
Book Now page: Proper alignment for the error messages should be fix.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#51]
![image](https://cloud.githubusercontent.com/assets/11186304/7081653/6a99d574-df78-11e4-920e-efa35595544b.png)

**Comment by christiancebudigital** [comment]
I am confused of what you want me to be fix with the image you posted above.. anyways error message alignment are now fixed.

**Comment by maluzynel** [comment]
Sorry I posted an incorrect screenshot image. Error messages are now properly aligned.
