### ISSUE TITLE
Book Now page: Better to disabled the textfield of Booking date to avoid invalid input.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#52]
![image](https://cloud.githubusercontent.com/assets/11186304/7081697/14cd675e-df79-11e4-9809-a694f93776aa.png)

**Comment by christiancebudigital** [comment]
This is not a bug,  if they have inputted invalid date, it will validate upon submission, this should be labeled as enhancement...

**Comment by maluzynel** [comment]
Invalid year inputted doesn't validate upon submission of the form. This is bug.

![image](https://cloud.githubusercontent.com/assets/11186304/7223232/b3715ada-e750-11e4-850d-3fb841e515b9.png)
