### ISSUE TITLE
Book Now page: Inconsistent height of option textfields in IE 8-11

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#59]
![image](https://cloud.githubusercontent.com/assets/11186304/7082445/e22fa010-df86-11e4-8060-f05eb636d576.png)

**Comment by maluzynel** [comment]
Not yet fixed in IE 7

![image](https://cloud.githubusercontent.com/assets/11186304/7223400/5e60bccc-e753-11e4-9aae-d89733bcfac0.png)

**Comment by christiancebudigital** [comment]
please clear your cache
![hit](https://cloud.githubusercontent.com/assets/11186331/7244511/1a0d5780-e80f-11e4-91a2-edc85ce85e48.png)

**Comment by maluzynel** [comment]
I have clear cached the browser and tried it to other PC as well.

![image](https://cloud.githubusercontent.com/assets/11186304/7247768/956205a4-e83f-11e4-8b58-8c1ff16bfa94.png)

**Comment by christiancebudigital** [comment]
working on my end..
