### ISSUE TITLE
Book Now page: Arrow down style of option fields are unsupported in IE 7-9 browser.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#60]
![image](https://cloud.githubusercontent.com/assets/11186304/7082463/45bb9d96-df87-11e4-947e-43f0f2a16e7f.png)

**Comment by christiancebudigital** [comment]
please clear cache on your browser..
![hit](https://cloud.githubusercontent.com/assets/11186331/7244489/ed283e38-e80e-11e4-9af8-d8dfd97e7c5d.png)

**Comment by maluzynel** [comment]
Im still able to replicate the issue.
