### ISSUE TITLE
Contact Us page: Contact details value should use 'Arial' font family.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#62]
![image](https://cloud.githubusercontent.com/assets/11186304/7082528/62a50dec-df88-11e4-9896-0defe90a95a4.png)

**Comment by christiancebudigital** [comment]
the font family you want to be changed is already in arial..

**Comment by maluzynel** [comment]
You're previously using a 'Helvetica Neue' font family. This is fixed.
