### ISSUE TITLE
Homepage - Content section: The two buttons in Firefox and IE browsers doesn't match up to the designs pecs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#87]
![image](https://cloud.githubusercontent.com/assets/11186304/7222932/0d52371e-e74b-11e4-8561-85c263b1620e.png)

**Comment by christiancebudigital** [comment]
![browser](https://cloud.githubusercontent.com/assets/11186331/7269700/ae97ca94-e908-11e4-952d-de1439cfcb20.jpg)
please clear cache working on my end...
