### ISSUE TITLE
Inner pages - Right sidebar: Default page link of post item should be from inner pages not a default 'untitled (draft)' page.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#91]
![image](https://cloud.githubusercontent.com/assets/11186304/7223066/c3eba706-e74d-11e4-84c1-7f7c9a5065c1.png)

![image](https://cloud.githubusercontent.com/assets/11186304/7223070/dddb81e0-e74d-11e4-978b-a92bcf4a811a.png)

**Comment by maluzynel** [comment]
Untitled draft should be removed

**Comment by christiancebudigital** [comment]
removed, 
note
dont create a post when you want to removed it, create post without title will cause to untitle draft..
