### ISSUE TITLE
Book Now page: Duration label of option field moved down in IE 7 browser.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#97]
![image](https://cloud.githubusercontent.com/assets/11186304/7223410/99b158ae-e753-11e4-8852-6889c5d864a5.png)

**Comment by christiancebudigital** [comment]
please clear cache.. working  on my end..
![book](https://cloud.githubusercontent.com/assets/11186331/7269178/eeda5f7c-e903-11e4-8ab4-91e1bbeeac82.jpg)
